-- tbl_categoria
-- nome, descricao, id_categoria
insert into tbl_categoria(nome, descricao) values('Iluminação', 'Sistemas de iluminação');
insert into tbl_categoria(nome, descricao) values('Bar e Mesa', 'Tudo para bar e mesa');
insert into tbl_categoria(nome, descricao) values('Objectos de Decoração', 'Decoração geral');
insert into tbl_categoria(nome, descricao) values('Mobiliário', 'Todos os móveis');
insert into tbl_categoria(nome, descricao) values('Têxteis-lar', 'Todos os tecidos');
insert into tbl_categoria(nome, descricao) values('Cozinha', 'Tudo para a sua cozinha');
insert into tbl_categoria(nome, descricao) values('Banho', 'Tudo para a sua casa de banho');
insert into tbl_categoria(nome, descricao) values('Jardim', 'Tudo para jardim');
insert into tbl_categoria(nome, descricao) values('Livros', 'Livros para sua leitura');
insert into tbl_categoria(nome, descricao, id_categoria) values('Iluminação de Mesa', 'descricao', 1);
insert into tbl_categoria(nome, descricao, id_categoria) values('Iluminação de Pé', 'descricao', 1);
insert into tbl_categoria(nome, descricao, id_categoria) values('Iluminação de Tecto', 'descricao', 1);
insert into tbl_categoria(nome, descricao, id_categoria) values('Iluminação de Tecto', 'descricao', 1);
insert into tbl_categoria(nome, descricao, id_categoria) values('Travessas', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Pratos', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Saladeiras', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Aperitivos / Tapas ', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Tabuleiros', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Açucareiros', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Acessórios de Chá', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Compoteiras', 'descricao', 2);
insert into tbl_categoria(nome, descricao, id_categoria) values('Jarras', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Castiçais', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Cinzeiros', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Relógios', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Porta CD', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Chaveiros', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Escritório', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Caixas', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Molduras', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Taças', 'descricao', 3);
insert into tbl_categoria(nome, descricao, id_categoria) values('Mesas', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Mesas de Apoio', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Carrinhos de Chá', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Bancos', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Sofás', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Pufs', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Camas', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Mesas Cabeceira', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Estantes', 'descricao', 4);
insert into tbl_categoria(nome, descricao, id_categoria) values('Toalhas de Mesa', 'descricao', 5);
insert into tbl_categoria(nome, descricao, id_categoria) values('Guardanapos', 'descricao', 5);
insert into tbl_categoria(nome, descricao, id_categoria) values('Almofadas', 'descricao', 5);
insert into tbl_categoria(nome, descricao, id_categoria) values('Mantas', 'descricao', 5);
insert into tbl_categoria(nome, descricao, id_categoria) values('Tapetes', 'descricao', 5);
insert into tbl_categoria(nome, descricao, id_categoria) values('Outros', 'descricao', 5);
insert into tbl_categoria(nome, descricao, id_categoria) values('Acessórios', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Acessórios para Fruta', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Colheres Gelado', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Tábuas', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Facas Cozinha', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Caixas para Pão', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Tachos e Frigideiras', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Sacos', 'descricao', 6);
insert into tbl_categoria(nome, descricao, id_categoria) values('Acessórios', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Cabides', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Armários', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Saboneteiras', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Doseadores e Copos', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Higiene Dentária', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Outros', 'descricao', 7);
insert into tbl_categoria(nome, descricao, id_categoria) values('Mesas', 'descricao', 8);
insert into tbl_categoria(nome, descricao, id_categoria) values('Caldeiras / Sofás', 'descricao', 8);
insert into tbl_categoria(nome, descricao, id_categoria) values('Barbeque', 'descricao', 8);
insert into tbl_categoria(nome, descricao, id_categoria) values('Outros', 'descricao', 8);
insert into tbl_categoria(nome, descricao, id_categoria) values('Arquitectura', 'descricao', 10);
insert into tbl_categoria(nome, descricao, id_categoria) values('Culinária', 'descricao', 10);
insert into tbl_categoria(nome, descricao, id_categoria) values('Criança', 'descricao', 10);
insert into tbl_categoria(nome, descricao, id_categoria) values('Outros', 'descricao', 10);