/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Tiny;
import jge2d.ResultadoColisao;

public class ArrastarTiny implements Colidivel {

    public ArrastarTiny() {
    }

    public void trataColisao(ResultadoColisao resultado){
        ((Tiny)resultado.resultadoObjecto2.objecto).getMovimentoActual().setPosicaoActual(resultado.resultadoObjecto2.pontoArraste, resultado.tempoColisao);
    }
}
