/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Suportavel;
import furyPackage.Tiny;
import furyPackage.estados.EstadoTiny;
import furyPackage.estados.EstadoTinySuportado;
import jge2d.ResultadoColisao;
import jge2d.jogo.movimentos.MovimentoTinyLivre;
import jge2d.jogo.movimentos.MovimentoVelocidadeComSentido;
public class AterrarTiny implements Colidivel {

    public AterrarTiny() {
    }

    public void trataColisao(ResultadoColisao resultado){
        Tiny heroi = (Tiny)resultado.resultadoObjecto1.objecto;
        Suportavel plataforma = (Suportavel)resultado.resultadoObjecto2.objecto;
        ((MovimentoTinyLivre)heroi.getMovimentoActual()).setSentidoDeslocamento(MovimentoVelocidadeComSentido.PARADO);
        heroi.mudarEstadoActual(EstadoTiny.SUPORTADO);
        ((EstadoTinySuportado)heroi.getEstadoActual()).aterrar(plataforma, resultado);
    }
}
