/* Generated by Together */

package furyPackage.collisionPackage;

import jge2d.ResultadoColisao;

public class ColisaoDefault implements Colidivel {

    public ColisaoDefault() {
    }

    public void trataColisao(ResultadoColisao resultado) {}
}
