/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Corda;
import furyPackage.Enganchavel;
import furyPackage.estados.EstadoCorda;
import furyPackage.estados.EstadoTiny;
import furyPackage.estados.HabilidadeCorda;
import jge2d.Ponto;
import jge2d.ResultadoColisao;
import jge2d.SpriteCorda;
import jge2d.jogo.movimentos.MovimentoTinyPenduradoNaCorda;

public class EngancharCorda implements Colidivel {

    public EngancharCorda() {
    }

    public void trataColisao(ResultadoColisao resultado) {
        Corda corda = (Corda)resultado.resultadoObjecto1.objecto;
        corda.getThisMovimento().parar(corda.getPontoDeEnganche());
        corda.mudarEstado(EstadoCorda.ENGANCHADA);
        corda.getHeroi().desSuportar(resultado.tempoColisao);
        corda.getHeroi().mudarEstadoActual(EstadoTiny.PENDURADO);
        ((MovimentoTinyPenduradoNaCorda)corda.getHeroi().getMovimentoActual()).setPosicoes(corda.getPontoDeEnganche(), new Ponto(corda.getHeroi().getSprite().getUltimaPosicao().getX(), corda.getHeroi().getSprite().getUltimaPosicao().getY() + 1), resultado.tempoColisao);
        corda.setEnganchado((Enganchavel)resultado.resultadoObjecto2.objecto);
        ((SpriteCorda)corda.getSprite()).setMovimentoDono(corda.getHeroi().getMovimentoActual());
        corda.getHeroi().getSprite().setAnimacao(HabilidadeCorda.PENDURADO, false, resultado.tempoColisao);
    }

}
