/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Corda;
import furyPackage.ObjectoDoNivel;
import jge2d.Ponto;
import jge2d.ResultadoColisao;
import jge2d.Sprite;

public class EngancharCordaEsquerda extends EngancharCorda {

    public EngancharCordaEsquerda() {
    }

    public void trataColisao(ResultadoColisao resultado) {
        Corda corda = (Corda)resultado.resultadoObjecto1.objecto;
        Sprite sprite = ((ObjectoDoNivel)resultado.resultadoObjecto2.objecto).getSprite();
        corda.setPontoDeEnganche(new Ponto(sprite.getUltimaPosicao().getX() - 1, corda.getSprite().getUltimaPosicao().getY()));
        super.trataColisao(resultado);
    }

}
