/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Tiny;
import jge2d.ResultadoColisao;
public class MatarTiny implements Colidivel {

    public MatarTiny() {
    }

    public void trataColisao(ResultadoColisao resultado){
        ((Tiny)resultado.resultadoObjecto2.objecto).morrer();
    }
}
