/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Corda;
import furyPackage.ObjectoDoNivel;
import jge2d.ResultadoColisao;
import jge2d.Sprite;

public class MovelEngancharCordaDireita extends EngancharCordaDireita {

    public MovelEngancharCordaDireita() {
    }

    public void trataColisao(ResultadoColisao resultado) {
        Corda corda = (Corda)resultado.resultadoObjecto1.objecto;
        Sprite sprite = ((ObjectoDoNivel)resultado.resultadoObjecto2.objecto).getSprite();

        super.trataColisao(resultado);
        corda.getHeroi().getMovimentoActual().setPosicaoRelativa(sprite.getMovimento(), resultado.tempoColisao);
        corda.getSprite().getMovimento().setPosicaoRelativa(sprite.getMovimento(), resultado.tempoColisao);
        corda.getHeroi().getSprite().setMovimento(corda.getHeroi().getMovimentoActual());
    }

}
