/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Tiny;
import furyPackage.estados.EstadoTinyLivre;
import jge2d.ResultadoColisao;
public class PararSaltoDoTinyPelosLados implements Colidivel {

    public PararSaltoDoTinyPelosLados() {
    }

    public void trataColisao(ResultadoColisao resultado){
        Tiny heroi = (Tiny)resultado.resultadoObjecto1.objecto;
        heroi.getMovimentoActual().setPosicaoActual(resultado.resultadoObjecto1.pontoArraste, resultado.tempoColisao);
        ((EstadoTinyLivre)heroi.getEstadoActual()).mudarSubEstado(resultado.resultadoObjecto1.tipoColisao / 4);
        heroi.parar(resultado.tempoColisao);
    }

}
