/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Tiny;
import jge2d.ResultadoColisao;
import jge2d.jogo.movimentos.MovimentoTinyLivre;
public class PararSaltoDoTinyPorCima implements Colidivel {

    public PararSaltoDoTinyPorCima() {
    }

    public void trataColisao(ResultadoColisao resultado){
        Tiny heroi = (Tiny)resultado.resultadoObjecto1.objecto;
        ((MovimentoTinyLivre)heroi.getMovimentoActual()).pararSalto();
        heroi.getMovimentoActual().setPosicaoActual(resultado.resultadoObjecto1.pontoArraste, resultado.tempoColisao);
    }
}
