/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Corda;
import jge2d.ResultadoColisao;

public class SuportavelRemoverCorda implements Colidivel {

    public SuportavelRemoverCorda() {
    }

    public void trataColisao(ResultadoColisao resultado) {
        ((Corda)resultado.resultadoObjecto1.objecto).remover(resultado.tempoColisao);
    }
}
