/* Generated by Together */

package furyPackage.collisionPackage;

import furyPackage.Fechadura;
import furyPackage.Tiny;
import jge2d.ResultadoColisao;
public class TinyAbrirFechadura implements Colidivel {

    public TinyAbrirFechadura() {
    }

    public void trataColisao(ResultadoColisao resultado){
        ((Tiny)resultado.resultadoObjecto1.objecto).abrirFechadura((Fechadura)resultado.resultadoObjecto2.objecto, resultado.tempoColisao);
    }
}
