//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace DataInjector.meteo {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetDireccaoVentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetHumidadeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetPrecipitacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetPressaoAtmosfericaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetRadiacaoSolarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetTemperaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetVelocidadeVentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_GetDataUltimaActualizacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresActuais_SelectAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback Variaveis_GetDescricaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Variaveis_GetNomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Variaveis_GetSimboloOperationCompleted;
        
        private System.Threading.SendOrPostCallback Variaveis_GetTempoAquisicaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Variaveis_GetUnidadeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Variaveis_SelectVariavelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetTemperaturaMaxByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetTemperaturaMinByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetVelocidadeVentoMaxByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetRadiacaoSolarMaxByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetPrecipitacaoTotalByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetNumHorasSolByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetHumidadeMaxByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetHumidadeMinByDataRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValoresDiarios_GetByDataRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::DataInjector.Properties.Settings.Default.DataInjector_meteo_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValoresActuais_GetDireccaoVentoCompletedEventHandler ValoresActuais_GetDireccaoVentoCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetHumidadeCompletedEventHandler ValoresActuais_GetHumidadeCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetPrecipitacaoCompletedEventHandler ValoresActuais_GetPrecipitacaoCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetPressaoAtmosfericaCompletedEventHandler ValoresActuais_GetPressaoAtmosfericaCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetRadiacaoSolarCompletedEventHandler ValoresActuais_GetRadiacaoSolarCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetTemperaturaCompletedEventHandler ValoresActuais_GetTemperaturaCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetVelocidadeVentoCompletedEventHandler ValoresActuais_GetVelocidadeVentoCompleted;
        
        /// <remarks/>
        public event ValoresActuais_GetDataUltimaActualizacaoCompletedEventHandler ValoresActuais_GetDataUltimaActualizacaoCompleted;
        
        /// <remarks/>
        public event ValoresActuais_SelectAllCompletedEventHandler ValoresActuais_SelectAllCompleted;
        
        /// <remarks/>
        public event Variaveis_GetDescricaoCompletedEventHandler Variaveis_GetDescricaoCompleted;
        
        /// <remarks/>
        public event Variaveis_GetNomeCompletedEventHandler Variaveis_GetNomeCompleted;
        
        /// <remarks/>
        public event Variaveis_GetSimboloCompletedEventHandler Variaveis_GetSimboloCompleted;
        
        /// <remarks/>
        public event Variaveis_GetTempoAquisicaoCompletedEventHandler Variaveis_GetTempoAquisicaoCompleted;
        
        /// <remarks/>
        public event Variaveis_GetUnidadeCompletedEventHandler Variaveis_GetUnidadeCompleted;
        
        /// <remarks/>
        public event Variaveis_SelectVariavelCompletedEventHandler Variaveis_SelectVariavelCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetTemperaturaMaxByDataRangeCompletedEventHandler ValoresDiarios_GetTemperaturaMaxByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetTemperaturaMinByDataRangeCompletedEventHandler ValoresDiarios_GetTemperaturaMinByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompletedEventHandler ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompletedEventHandler ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompletedEventHandler ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompletedEventHandler ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompletedEventHandler ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetNumHorasSolByDataRangeCompletedEventHandler ValoresDiarios_GetNumHorasSolByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetHumidadeMaxByDataRangeCompletedEventHandler ValoresDiarios_GetHumidadeMaxByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetHumidadeMinByDataRangeCompletedEventHandler ValoresDiarios_GetHumidadeMinByDataRangeCompleted;
        
        /// <remarks/>
        public event ValoresDiarios_GetByDataRangeCompletedEventHandler ValoresDiarios_GetByDataRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetDireccaoVento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetDireccaoVento() {
            object[] results = this.Invoke("ValoresActuais_GetDireccaoVento", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetDireccaoVentoAsync() {
            this.ValoresActuais_GetDireccaoVentoAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetDireccaoVentoAsync(object userState) {
            if ((this.ValoresActuais_GetDireccaoVentoOperationCompleted == null)) {
                this.ValoresActuais_GetDireccaoVentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetDireccaoVentoOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetDireccaoVento", new object[0], this.ValoresActuais_GetDireccaoVentoOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetDireccaoVentoOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetDireccaoVentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetDireccaoVentoCompleted(this, new ValoresActuais_GetDireccaoVentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetHumidade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetHumidade() {
            object[] results = this.Invoke("ValoresActuais_GetHumidade", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetHumidadeAsync() {
            this.ValoresActuais_GetHumidadeAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetHumidadeAsync(object userState) {
            if ((this.ValoresActuais_GetHumidadeOperationCompleted == null)) {
                this.ValoresActuais_GetHumidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetHumidadeOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetHumidade", new object[0], this.ValoresActuais_GetHumidadeOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetHumidadeOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetHumidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetHumidadeCompleted(this, new ValoresActuais_GetHumidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetPrecipitacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetPrecipitacao() {
            object[] results = this.Invoke("ValoresActuais_GetPrecipitacao", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetPrecipitacaoAsync() {
            this.ValoresActuais_GetPrecipitacaoAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetPrecipitacaoAsync(object userState) {
            if ((this.ValoresActuais_GetPrecipitacaoOperationCompleted == null)) {
                this.ValoresActuais_GetPrecipitacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetPrecipitacaoOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetPrecipitacao", new object[0], this.ValoresActuais_GetPrecipitacaoOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetPrecipitacaoOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetPrecipitacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetPrecipitacaoCompleted(this, new ValoresActuais_GetPrecipitacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetPressaoAtmosferica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetPressaoAtmosferica() {
            object[] results = this.Invoke("ValoresActuais_GetPressaoAtmosferica", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetPressaoAtmosfericaAsync() {
            this.ValoresActuais_GetPressaoAtmosfericaAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetPressaoAtmosfericaAsync(object userState) {
            if ((this.ValoresActuais_GetPressaoAtmosfericaOperationCompleted == null)) {
                this.ValoresActuais_GetPressaoAtmosfericaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetPressaoAtmosfericaOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetPressaoAtmosferica", new object[0], this.ValoresActuais_GetPressaoAtmosfericaOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetPressaoAtmosfericaOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetPressaoAtmosfericaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetPressaoAtmosfericaCompleted(this, new ValoresActuais_GetPressaoAtmosfericaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetRadiacaoSolar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetRadiacaoSolar() {
            object[] results = this.Invoke("ValoresActuais_GetRadiacaoSolar", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetRadiacaoSolarAsync() {
            this.ValoresActuais_GetRadiacaoSolarAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetRadiacaoSolarAsync(object userState) {
            if ((this.ValoresActuais_GetRadiacaoSolarOperationCompleted == null)) {
                this.ValoresActuais_GetRadiacaoSolarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetRadiacaoSolarOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetRadiacaoSolar", new object[0], this.ValoresActuais_GetRadiacaoSolarOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetRadiacaoSolarOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetRadiacaoSolarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetRadiacaoSolarCompleted(this, new ValoresActuais_GetRadiacaoSolarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetTemperatura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetTemperatura() {
            object[] results = this.Invoke("ValoresActuais_GetTemperatura", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetTemperaturaAsync() {
            this.ValoresActuais_GetTemperaturaAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetTemperaturaAsync(object userState) {
            if ((this.ValoresActuais_GetTemperaturaOperationCompleted == null)) {
                this.ValoresActuais_GetTemperaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetTemperaturaOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetTemperatura", new object[0], this.ValoresActuais_GetTemperaturaOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetTemperaturaOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetTemperaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetTemperaturaCompleted(this, new ValoresActuais_GetTemperaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetVelocidadeVento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float ValoresActuais_GetVelocidadeVento() {
            object[] results = this.Invoke("ValoresActuais_GetVelocidadeVento", new object[0]);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetVelocidadeVentoAsync() {
            this.ValoresActuais_GetVelocidadeVentoAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetVelocidadeVentoAsync(object userState) {
            if ((this.ValoresActuais_GetVelocidadeVentoOperationCompleted == null)) {
                this.ValoresActuais_GetVelocidadeVentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetVelocidadeVentoOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetVelocidadeVento", new object[0], this.ValoresActuais_GetVelocidadeVentoOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetVelocidadeVentoOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetVelocidadeVentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetVelocidadeVentoCompleted(this, new ValoresActuais_GetVelocidadeVentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_GetDataUltimaActualizacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime ValoresActuais_GetDataUltimaActualizacao() {
            object[] results = this.Invoke("ValoresActuais_GetDataUltimaActualizacao", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_GetDataUltimaActualizacaoAsync() {
            this.ValoresActuais_GetDataUltimaActualizacaoAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_GetDataUltimaActualizacaoAsync(object userState) {
            if ((this.ValoresActuais_GetDataUltimaActualizacaoOperationCompleted == null)) {
                this.ValoresActuais_GetDataUltimaActualizacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_GetDataUltimaActualizacaoOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_GetDataUltimaActualizacao", new object[0], this.ValoresActuais_GetDataUltimaActualizacaoOperationCompleted, userState);
        }
        
        private void OnValoresActuais_GetDataUltimaActualizacaoOperationCompleted(object arg) {
            if ((this.ValoresActuais_GetDataUltimaActualizacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_GetDataUltimaActualizacaoCompleted(this, new ValoresActuais_GetDataUltimaActualizacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresActuais_SelectAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CValoresActuais ValoresActuais_SelectAll() {
            object[] results = this.Invoke("ValoresActuais_SelectAll", new object[0]);
            return ((CValoresActuais)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresActuais_SelectAllAsync() {
            this.ValoresActuais_SelectAllAsync(null);
        }
        
        /// <remarks/>
        public void ValoresActuais_SelectAllAsync(object userState) {
            if ((this.ValoresActuais_SelectAllOperationCompleted == null)) {
                this.ValoresActuais_SelectAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresActuais_SelectAllOperationCompleted);
            }
            this.InvokeAsync("ValoresActuais_SelectAll", new object[0], this.ValoresActuais_SelectAllOperationCompleted, userState);
        }
        
        private void OnValoresActuais_SelectAllOperationCompleted(object arg) {
            if ((this.ValoresActuais_SelectAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresActuais_SelectAllCompleted(this, new ValoresActuais_SelectAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Variaveis_GetDescricao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Variaveis_GetDescricao(string variavel) {
            object[] results = this.Invoke("Variaveis_GetDescricao", new object[] {
                        variavel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Variaveis_GetDescricaoAsync(string variavel) {
            this.Variaveis_GetDescricaoAsync(variavel, null);
        }
        
        /// <remarks/>
        public void Variaveis_GetDescricaoAsync(string variavel, object userState) {
            if ((this.Variaveis_GetDescricaoOperationCompleted == null)) {
                this.Variaveis_GetDescricaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariaveis_GetDescricaoOperationCompleted);
            }
            this.InvokeAsync("Variaveis_GetDescricao", new object[] {
                        variavel}, this.Variaveis_GetDescricaoOperationCompleted, userState);
        }
        
        private void OnVariaveis_GetDescricaoOperationCompleted(object arg) {
            if ((this.Variaveis_GetDescricaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Variaveis_GetDescricaoCompleted(this, new Variaveis_GetDescricaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Variaveis_GetNome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Variaveis_GetNome(string variavel) {
            object[] results = this.Invoke("Variaveis_GetNome", new object[] {
                        variavel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Variaveis_GetNomeAsync(string variavel) {
            this.Variaveis_GetNomeAsync(variavel, null);
        }
        
        /// <remarks/>
        public void Variaveis_GetNomeAsync(string variavel, object userState) {
            if ((this.Variaveis_GetNomeOperationCompleted == null)) {
                this.Variaveis_GetNomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariaveis_GetNomeOperationCompleted);
            }
            this.InvokeAsync("Variaveis_GetNome", new object[] {
                        variavel}, this.Variaveis_GetNomeOperationCompleted, userState);
        }
        
        private void OnVariaveis_GetNomeOperationCompleted(object arg) {
            if ((this.Variaveis_GetNomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Variaveis_GetNomeCompleted(this, new Variaveis_GetNomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Variaveis_GetSimbolo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Variaveis_GetSimbolo(string variavel) {
            object[] results = this.Invoke("Variaveis_GetSimbolo", new object[] {
                        variavel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Variaveis_GetSimboloAsync(string variavel) {
            this.Variaveis_GetSimboloAsync(variavel, null);
        }
        
        /// <remarks/>
        public void Variaveis_GetSimboloAsync(string variavel, object userState) {
            if ((this.Variaveis_GetSimboloOperationCompleted == null)) {
                this.Variaveis_GetSimboloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariaveis_GetSimboloOperationCompleted);
            }
            this.InvokeAsync("Variaveis_GetSimbolo", new object[] {
                        variavel}, this.Variaveis_GetSimboloOperationCompleted, userState);
        }
        
        private void OnVariaveis_GetSimboloOperationCompleted(object arg) {
            if ((this.Variaveis_GetSimboloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Variaveis_GetSimboloCompleted(this, new Variaveis_GetSimboloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Variaveis_GetTempoAquisicao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Variaveis_GetTempoAquisicao(string variavel) {
            object[] results = this.Invoke("Variaveis_GetTempoAquisicao", new object[] {
                        variavel});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Variaveis_GetTempoAquisicaoAsync(string variavel) {
            this.Variaveis_GetTempoAquisicaoAsync(variavel, null);
        }
        
        /// <remarks/>
        public void Variaveis_GetTempoAquisicaoAsync(string variavel, object userState) {
            if ((this.Variaveis_GetTempoAquisicaoOperationCompleted == null)) {
                this.Variaveis_GetTempoAquisicaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariaveis_GetTempoAquisicaoOperationCompleted);
            }
            this.InvokeAsync("Variaveis_GetTempoAquisicao", new object[] {
                        variavel}, this.Variaveis_GetTempoAquisicaoOperationCompleted, userState);
        }
        
        private void OnVariaveis_GetTempoAquisicaoOperationCompleted(object arg) {
            if ((this.Variaveis_GetTempoAquisicaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Variaveis_GetTempoAquisicaoCompleted(this, new Variaveis_GetTempoAquisicaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Variaveis_GetUnidade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Variaveis_GetUnidade(string variavel) {
            object[] results = this.Invoke("Variaveis_GetUnidade", new object[] {
                        variavel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Variaveis_GetUnidadeAsync(string variavel) {
            this.Variaveis_GetUnidadeAsync(variavel, null);
        }
        
        /// <remarks/>
        public void Variaveis_GetUnidadeAsync(string variavel, object userState) {
            if ((this.Variaveis_GetUnidadeOperationCompleted == null)) {
                this.Variaveis_GetUnidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariaveis_GetUnidadeOperationCompleted);
            }
            this.InvokeAsync("Variaveis_GetUnidade", new object[] {
                        variavel}, this.Variaveis_GetUnidadeOperationCompleted, userState);
        }
        
        private void OnVariaveis_GetUnidadeOperationCompleted(object arg) {
            if ((this.Variaveis_GetUnidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Variaveis_GetUnidadeCompleted(this, new Variaveis_GetUnidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Variaveis_SelectVariavel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Variaveis_SelectVariavel(string variavel) {
            object[] results = this.Invoke("Variaveis_SelectVariavel", new object[] {
                        variavel});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Variaveis_SelectVariavelAsync(string variavel) {
            this.Variaveis_SelectVariavelAsync(variavel, null);
        }
        
        /// <remarks/>
        public void Variaveis_SelectVariavelAsync(string variavel, object userState) {
            if ((this.Variaveis_SelectVariavelOperationCompleted == null)) {
                this.Variaveis_SelectVariavelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariaveis_SelectVariavelOperationCompleted);
            }
            this.InvokeAsync("Variaveis_SelectVariavel", new object[] {
                        variavel}, this.Variaveis_SelectVariavelOperationCompleted, userState);
        }
        
        private void OnVariaveis_SelectVariavelOperationCompleted(object arg) {
            if ((this.Variaveis_SelectVariavelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Variaveis_SelectVariavelCompleted(this, new Variaveis_SelectVariavelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetTemperaturaMaxByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetTemperaturaMaxByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetTemperaturaMaxByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetTemperaturaMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetTemperaturaMaxByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetTemperaturaMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetTemperaturaMaxByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetTemperaturaMaxByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetTemperaturaMaxByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetTemperaturaMaxByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetTemperaturaMaxByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetTemperaturaMaxByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetTemperaturaMaxByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetTemperaturaMaxByDataRangeCompleted(this, new ValoresDiarios_GetTemperaturaMaxByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetTemperaturaMinByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetTemperaturaMinByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetTemperaturaMinByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetTemperaturaMinByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetTemperaturaMinByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetTemperaturaMinByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetTemperaturaMinByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetTemperaturaMinByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetTemperaturaMinByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetTemperaturaMinByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetTemperaturaMinByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetTemperaturaMinByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetTemperaturaMinByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetTemperaturaMinByDataRangeCompleted(this, new ValoresDiarios_GetTemperaturaMinByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetVelocidadeVentoMaxByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetVelocidadeVentoMaxByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetVelocidadeVentoMaxByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetVelocidadeVentoMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetVelocidadeVentoMaxByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetVelocidadeVentoMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetVelocidadeVentoMaxByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetVelocidadeVentoMaxByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetVelocidadeVentoMaxByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetVelocidadeVentoMaxByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetVelocidadeVentoMaxByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetVelocidadeVentoMaxByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompleted(this, new ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetRadiacaoSolarMaxByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetRadiacaoSolarMaxByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetRadiacaoSolarMaxByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetRadiacaoSolarMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetRadiacaoSolarMaxByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetRadiacaoSolarMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetRadiacaoSolarMaxByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetRadiacaoSolarMaxByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetRadiacaoSolarMaxByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetRadiacaoSolarMaxByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetRadiacaoSolarMaxByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetRadiacaoSolarMaxByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompleted(this, new ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetPressaoAtmosfericaMaxByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetPressaoAtmosfericaMaxByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetPressaoAtmosfericaMaxByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetPressaoAtmosfericaMaxByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompleted(this, new ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetPressaoAtmosfericaMinByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetPressaoAtmosfericaMinByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetPressaoAtmosfericaMinByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetPressaoAtmosfericaMinByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetPressaoAtmosfericaMinByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetPressaoAtmosfericaMinByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompleted(this, new ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetPrecipitacaoTotalByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetPrecipitacaoTotalByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetPrecipitacaoTotalByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetPrecipitacaoTotalByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetPrecipitacaoTotalByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetPrecipitacaoTotalByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetPrecipitacaoTotalByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetPrecipitacaoTotalByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetPrecipitacaoTotalByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetPrecipitacaoTotalByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetPrecipitacaoTotalByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetPrecipitacaoTotalByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompleted(this, new ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetNumHorasSolByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetNumHorasSolByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetNumHorasSolByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetNumHorasSolByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetNumHorasSolByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetNumHorasSolByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetNumHorasSolByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetNumHorasSolByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetNumHorasSolByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetNumHorasSolByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetNumHorasSolByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetNumHorasSolByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetNumHorasSolByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetNumHorasSolByDataRangeCompleted(this, new ValoresDiarios_GetNumHorasSolByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetHumidadeMaxByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetHumidadeMaxByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetHumidadeMaxByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetHumidadeMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetHumidadeMaxByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetHumidadeMaxByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetHumidadeMaxByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetHumidadeMaxByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetHumidadeMaxByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetHumidadeMaxByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetHumidadeMaxByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetHumidadeMaxByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetHumidadeMaxByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetHumidadeMaxByDataRangeCompleted(this, new ValoresDiarios_GetHumidadeMaxByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetHumidadeMinByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetHumidadeMinByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetHumidadeMinByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetHumidadeMinByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetHumidadeMinByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetHumidadeMinByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetHumidadeMinByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetHumidadeMinByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetHumidadeMinByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetHumidadeMinByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetHumidadeMinByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetHumidadeMinByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetHumidadeMinByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetHumidadeMinByDataRangeCompleted(this, new ValoresDiarios_GetHumidadeMinByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValoresDiarios_GetByDataRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValoresDiarios_GetByDataRange(System.DateTime dataini, System.DateTime datafim) {
            object[] results = this.Invoke("ValoresDiarios_GetByDataRange", new object[] {
                        dataini,
                        datafim});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetByDataRangeAsync(System.DateTime dataini, System.DateTime datafim) {
            this.ValoresDiarios_GetByDataRangeAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void ValoresDiarios_GetByDataRangeAsync(System.DateTime dataini, System.DateTime datafim, object userState) {
            if ((this.ValoresDiarios_GetByDataRangeOperationCompleted == null)) {
                this.ValoresDiarios_GetByDataRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValoresDiarios_GetByDataRangeOperationCompleted);
            }
            this.InvokeAsync("ValoresDiarios_GetByDataRange", new object[] {
                        dataini,
                        datafim}, this.ValoresDiarios_GetByDataRangeOperationCompleted, userState);
        }
        
        private void OnValoresDiarios_GetByDataRangeOperationCompleted(object arg) {
            if ((this.ValoresDiarios_GetByDataRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValoresDiarios_GetByDataRangeCompleted(this, new ValoresDiarios_GetByDataRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CValoresActuais {
        
        private short id_ValoresActuais_SqlTypeField;
        
        private float temperatura_SqlTypeField;
        
        private float humidade_SqlTypeField;
        
        private float pressaoAtmosferica_SqlTypeField;
        
        private float velocidadeVento_SqlTypeField;
        
        private float direccaoVento_SqlTypeField;
        
        private float radiacaoSolar_SqlTypeField;
        
        private float precipitacao_SqlTypeField;
        
        private System.DateTime hora_Precipitacao_SqlTypeField;
        
        private short id_ValoresActuaisField;
        
        private float temperaturaField;
        
        private float humidadeField;
        
        private float pressaoAtmosfericaField;
        
        private float velocidadeVentoField;
        
        private float direccaoVentoField;
        
        private float radiacaoSolarField;
        
        private float precipitacaoField;
        
        private System.DateTime hora_PrecipitacaoField;
        
        /// <remarks/>
        public short Id_ValoresActuais_SqlType {
            get {
                return this.id_ValoresActuais_SqlTypeField;
            }
            set {
                this.id_ValoresActuais_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float Temperatura_SqlType {
            get {
                return this.temperatura_SqlTypeField;
            }
            set {
                this.temperatura_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float Humidade_SqlType {
            get {
                return this.humidade_SqlTypeField;
            }
            set {
                this.humidade_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float PressaoAtmosferica_SqlType {
            get {
                return this.pressaoAtmosferica_SqlTypeField;
            }
            set {
                this.pressaoAtmosferica_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float VelocidadeVento_SqlType {
            get {
                return this.velocidadeVento_SqlTypeField;
            }
            set {
                this.velocidadeVento_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float DireccaoVento_SqlType {
            get {
                return this.direccaoVento_SqlTypeField;
            }
            set {
                this.direccaoVento_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float RadiacaoSolar_SqlType {
            get {
                return this.radiacaoSolar_SqlTypeField;
            }
            set {
                this.radiacaoSolar_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public float Precipitacao_SqlType {
            get {
                return this.precipitacao_SqlTypeField;
            }
            set {
                this.precipitacao_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Hora_Precipitacao_SqlType {
            get {
                return this.hora_Precipitacao_SqlTypeField;
            }
            set {
                this.hora_Precipitacao_SqlTypeField = value;
            }
        }
        
        /// <remarks/>
        public short Id_ValoresActuais {
            get {
                return this.id_ValoresActuaisField;
            }
            set {
                this.id_ValoresActuaisField = value;
            }
        }
        
        /// <remarks/>
        public float Temperatura {
            get {
                return this.temperaturaField;
            }
            set {
                this.temperaturaField = value;
            }
        }
        
        /// <remarks/>
        public float Humidade {
            get {
                return this.humidadeField;
            }
            set {
                this.humidadeField = value;
            }
        }
        
        /// <remarks/>
        public float PressaoAtmosferica {
            get {
                return this.pressaoAtmosfericaField;
            }
            set {
                this.pressaoAtmosfericaField = value;
            }
        }
        
        /// <remarks/>
        public float VelocidadeVento {
            get {
                return this.velocidadeVentoField;
            }
            set {
                this.velocidadeVentoField = value;
            }
        }
        
        /// <remarks/>
        public float DireccaoVento {
            get {
                return this.direccaoVentoField;
            }
            set {
                this.direccaoVentoField = value;
            }
        }
        
        /// <remarks/>
        public float RadiacaoSolar {
            get {
                return this.radiacaoSolarField;
            }
            set {
                this.radiacaoSolarField = value;
            }
        }
        
        /// <remarks/>
        public float Precipitacao {
            get {
                return this.precipitacaoField;
            }
            set {
                this.precipitacaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Hora_Precipitacao {
            get {
                return this.hora_PrecipitacaoField;
            }
            set {
                this.hora_PrecipitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetDireccaoVentoCompletedEventHandler(object sender, ValoresActuais_GetDireccaoVentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetDireccaoVentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetDireccaoVentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetHumidadeCompletedEventHandler(object sender, ValoresActuais_GetHumidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetHumidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetHumidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetPrecipitacaoCompletedEventHandler(object sender, ValoresActuais_GetPrecipitacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetPrecipitacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetPrecipitacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetPressaoAtmosfericaCompletedEventHandler(object sender, ValoresActuais_GetPressaoAtmosfericaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetPressaoAtmosfericaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetPressaoAtmosfericaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetRadiacaoSolarCompletedEventHandler(object sender, ValoresActuais_GetRadiacaoSolarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetRadiacaoSolarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetRadiacaoSolarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetTemperaturaCompletedEventHandler(object sender, ValoresActuais_GetTemperaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetTemperaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetTemperaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetVelocidadeVentoCompletedEventHandler(object sender, ValoresActuais_GetVelocidadeVentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetVelocidadeVentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetVelocidadeVentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_GetDataUltimaActualizacaoCompletedEventHandler(object sender, ValoresActuais_GetDataUltimaActualizacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_GetDataUltimaActualizacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_GetDataUltimaActualizacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresActuais_SelectAllCompletedEventHandler(object sender, ValoresActuais_SelectAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresActuais_SelectAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresActuais_SelectAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CValoresActuais Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CValoresActuais)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void Variaveis_GetDescricaoCompletedEventHandler(object sender, Variaveis_GetDescricaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Variaveis_GetDescricaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Variaveis_GetDescricaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void Variaveis_GetNomeCompletedEventHandler(object sender, Variaveis_GetNomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Variaveis_GetNomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Variaveis_GetNomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void Variaveis_GetSimboloCompletedEventHandler(object sender, Variaveis_GetSimboloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Variaveis_GetSimboloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Variaveis_GetSimboloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void Variaveis_GetTempoAquisicaoCompletedEventHandler(object sender, Variaveis_GetTempoAquisicaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Variaveis_GetTempoAquisicaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Variaveis_GetTempoAquisicaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void Variaveis_GetUnidadeCompletedEventHandler(object sender, Variaveis_GetUnidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Variaveis_GetUnidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Variaveis_GetUnidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void Variaveis_SelectVariavelCompletedEventHandler(object sender, Variaveis_SelectVariavelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Variaveis_SelectVariavelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Variaveis_SelectVariavelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetTemperaturaMaxByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetTemperaturaMaxByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetTemperaturaMaxByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetTemperaturaMaxByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetTemperaturaMinByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetTemperaturaMinByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetTemperaturaMinByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetTemperaturaMinByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetVelocidadeVentoMaxByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetRadiacaoSolarMaxByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetPressaoAtmosfericaMaxByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetPressaoAtmosfericaMinByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetPrecipitacaoTotalByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetNumHorasSolByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetNumHorasSolByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetNumHorasSolByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetNumHorasSolByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetHumidadeMaxByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetHumidadeMaxByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetHumidadeMaxByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetHumidadeMaxByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetHumidadeMinByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetHumidadeMinByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetHumidadeMinByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetHumidadeMinByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ValoresDiarios_GetByDataRangeCompletedEventHandler(object sender, ValoresDiarios_GetByDataRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValoresDiarios_GetByDataRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValoresDiarios_GetByDataRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591