//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace NodeConfig.NodeService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://iadatabus.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setParentOperationCompleted;
        
        private System.Threading.SendOrPostCallback addDataTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeDataTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback unSubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryServerSubscribedDataServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryDataServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryServersOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParentServersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::NodeConfig.Properties.Settings.Default.NodeConfig_NodeService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setParentCompletedEventHandler setParentCompleted;
        
        /// <remarks/>
        public event addDataTypeCompletedEventHandler addDataTypeCompleted;
        
        /// <remarks/>
        public event removeDataTypeCompletedEventHandler removeDataTypeCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event SubscribeCompletedEventHandler SubscribeCompleted;
        
        /// <remarks/>
        public event unSubscribeCompletedEventHandler unSubscribeCompleted;
        
        /// <remarks/>
        public event RecDataCompletedEventHandler RecDataCompleted;
        
        /// <remarks/>
        public event QueryServerSubscribedDataServicesCompletedEventHandler QueryServerSubscribedDataServicesCompleted;
        
        /// <remarks/>
        public event QueryDataServiceCompletedEventHandler QueryDataServiceCompleted;
        
        /// <remarks/>
        public event QueryServersCompletedEventHandler QueryServersCompleted;
        
        /// <remarks/>
        public event QueryParentServersCompletedEventHandler QueryParentServersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/setParent", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setParent(string url) {
            object[] results = this.Invoke("setParent", new object[] {
                        url});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setParentAsync(string url) {
            this.setParentAsync(url, null);
        }
        
        /// <remarks/>
        public void setParentAsync(string url, object userState) {
            if ((this.setParentOperationCompleted == null)) {
                this.setParentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetParentOperationCompleted);
            }
            this.InvokeAsync("setParent", new object[] {
                        url}, this.setParentOperationCompleted, userState);
        }
        
        private void OnsetParentOperationCompleted(object arg) {
            if ((this.setParentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setParentCompleted(this, new setParentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/addDataType", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addDataType(string type) {
            this.Invoke("addDataType", new object[] {
                        type});
        }
        
        /// <remarks/>
        public void addDataTypeAsync(string type) {
            this.addDataTypeAsync(type, null);
        }
        
        /// <remarks/>
        public void addDataTypeAsync(string type, object userState) {
            if ((this.addDataTypeOperationCompleted == null)) {
                this.addDataTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddDataTypeOperationCompleted);
            }
            this.InvokeAsync("addDataType", new object[] {
                        type}, this.addDataTypeOperationCompleted, userState);
        }
        
        private void OnaddDataTypeOperationCompleted(object arg) {
            if ((this.addDataTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addDataTypeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/removeDataType", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removeDataType(string type) {
            this.Invoke("removeDataType", new object[] {
                        type});
        }
        
        /// <remarks/>
        public void removeDataTypeAsync(string type) {
            this.removeDataTypeAsync(type, null);
        }
        
        /// <remarks/>
        public void removeDataTypeAsync(string type, object userState) {
            if ((this.removeDataTypeOperationCompleted == null)) {
                this.removeDataTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveDataTypeOperationCompleted);
            }
            this.InvokeAsync("removeDataType", new object[] {
                        type}, this.removeDataTypeOperationCompleted, userState);
        }
        
        private void OnremoveDataTypeOperationCompleted(object arg) {
            if ((this.removeDataTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeDataTypeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/Register", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Register(string url) {
            object[] results = this.Invoke("Register", new object[] {
                        url});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string url) {
            this.RegisterAsync(url, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string url, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        url}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/Subscribe", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Subscribe(string url, string service) {
            object[] results = this.Invoke("Subscribe", new object[] {
                        url,
                        service});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubscribeAsync(string url, string service) {
            this.SubscribeAsync(url, service, null);
        }
        
        /// <remarks/>
        public void SubscribeAsync(string url, string service, object userState) {
            if ((this.SubscribeOperationCompleted == null)) {
                this.SubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubscribeOperationCompleted);
            }
            this.InvokeAsync("Subscribe", new object[] {
                        url,
                        service}, this.SubscribeOperationCompleted, userState);
        }
        
        private void OnSubscribeOperationCompleted(object arg) {
            if ((this.SubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubscribeCompleted(this, new SubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/unSubscribe", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string unSubscribe(string url, string service) {
            object[] results = this.Invoke("unSubscribe", new object[] {
                        url,
                        service});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void unSubscribeAsync(string url, string service) {
            this.unSubscribeAsync(url, service, null);
        }
        
        /// <remarks/>
        public void unSubscribeAsync(string url, string service, object userState) {
            if ((this.unSubscribeOperationCompleted == null)) {
                this.unSubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunSubscribeOperationCompleted);
            }
            this.InvokeAsync("unSubscribe", new object[] {
                        url,
                        service}, this.unSubscribeOperationCompleted, userState);
        }
        
        private void OnunSubscribeOperationCompleted(object arg) {
            if ((this.unSubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unSubscribeCompleted(this, new unSubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/RecData", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecData(string xml) {
            object[] results = this.Invoke("RecData", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecDataAsync(string xml) {
            this.RecDataAsync(xml, null);
        }
        
        /// <remarks/>
        public void RecDataAsync(string xml, object userState) {
            if ((this.RecDataOperationCompleted == null)) {
                this.RecDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecDataOperationCompleted);
            }
            this.InvokeAsync("RecData", new object[] {
                        xml}, this.RecDataOperationCompleted, userState);
        }
        
        private void OnRecDataOperationCompleted(object arg) {
            if ((this.RecDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecDataCompleted(this, new RecDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/QueryServerSubscribedDataServices", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryServerSubscribedDataServices(string url) {
            object[] results = this.Invoke("QueryServerSubscribedDataServices", new object[] {
                        url});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryServerSubscribedDataServicesAsync(string url) {
            this.QueryServerSubscribedDataServicesAsync(url, null);
        }
        
        /// <remarks/>
        public void QueryServerSubscribedDataServicesAsync(string url, object userState) {
            if ((this.QueryServerSubscribedDataServicesOperationCompleted == null)) {
                this.QueryServerSubscribedDataServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryServerSubscribedDataServicesOperationCompleted);
            }
            this.InvokeAsync("QueryServerSubscribedDataServices", new object[] {
                        url}, this.QueryServerSubscribedDataServicesOperationCompleted, userState);
        }
        
        private void OnQueryServerSubscribedDataServicesOperationCompleted(object arg) {
            if ((this.QueryServerSubscribedDataServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryServerSubscribedDataServicesCompleted(this, new QueryServerSubscribedDataServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/QueryDataService", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryDataService() {
            object[] results = this.Invoke("QueryDataService", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDataServiceAsync() {
            this.QueryDataServiceAsync(null);
        }
        
        /// <remarks/>
        public void QueryDataServiceAsync(object userState) {
            if ((this.QueryDataServiceOperationCompleted == null)) {
                this.QueryDataServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDataServiceOperationCompleted);
            }
            this.InvokeAsync("QueryDataService", new object[0], this.QueryDataServiceOperationCompleted, userState);
        }
        
        private void OnQueryDataServiceOperationCompleted(object arg) {
            if ((this.QueryDataServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDataServiceCompleted(this, new QueryDataServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/QueryServers", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryServers() {
            object[] results = this.Invoke("QueryServers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryServersAsync() {
            this.QueryServersAsync(null);
        }
        
        /// <remarks/>
        public void QueryServersAsync(object userState) {
            if ((this.QueryServersOperationCompleted == null)) {
                this.QueryServersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryServersOperationCompleted);
            }
            this.InvokeAsync("QueryServers", new object[0], this.QueryServersOperationCompleted, userState);
        }
        
        private void OnQueryServersOperationCompleted(object arg) {
            if ((this.QueryServersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryServersCompleted(this, new QueryServersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://iadatabus.org/QueryParentServers", RequestNamespace="http://iadatabus.org/", ResponseNamespace="http://iadatabus.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParentServers() {
            object[] results = this.Invoke("QueryParentServers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParentServersAsync() {
            this.QueryParentServersAsync(null);
        }
        
        /// <remarks/>
        public void QueryParentServersAsync(object userState) {
            if ((this.QueryParentServersOperationCompleted == null)) {
                this.QueryParentServersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParentServersOperationCompleted);
            }
            this.InvokeAsync("QueryParentServers", new object[0], this.QueryParentServersOperationCompleted, userState);
        }
        
        private void OnQueryParentServersOperationCompleted(object arg) {
            if ((this.QueryParentServersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParentServersCompleted(this, new QueryParentServersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void setParentCompletedEventHandler(object sender, setParentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void addDataTypeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void removeDataTypeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void SubscribeCompletedEventHandler(object sender, SubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void unSubscribeCompletedEventHandler(object sender, unSubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unSubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unSubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void RecDataCompletedEventHandler(object sender, RecDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void QueryServerSubscribedDataServicesCompletedEventHandler(object sender, QueryServerSubscribedDataServicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryServerSubscribedDataServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryServerSubscribedDataServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void QueryDataServiceCompletedEventHandler(object sender, QueryDataServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDataServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDataServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void QueryServersCompletedEventHandler(object sender, QueryServersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryServersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryServersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void QueryParentServersCompletedEventHandler(object sender, QueryParentServersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParentServersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParentServersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591