/* Generated by Together */

package furyPackage;

import jge2d.Ponto;

/**
 * Agrupa todos os objectos activáveis que possuem uma porta associada
 */
public abstract class ActivavelComPorta extends Activavel {

    /**
     * Porta que está associada ao activável com porta
     */
    private Porta porta;

    public ActivavelComPorta() {
    }

    /**
     * @param posicao - Posicao do objecto no nível
     * @param nivel - Nível ao qual pertence o objecto
     * @param porta - Porta a associar ao objecto activável com porta
     */
    public ActivavelComPorta(String nome, Ponto posicao, Nivel nivel, Porta porta) {
        super(nome, posicao, nivel);
        this.porta = porta;
    }

    /**
     * Pede à porta para se activar (abrir)
     */
    public void abrirPorta(long tempo) {
        porta.abrir(tempo);
    }

    public Porta getPorta() {
        return porta;
    }

    public void setPorta(Porta porta) {
        this.porta = porta;
    }

}
