/* Generated by Together */

package furyPackage;

import jge2d.ResultadoColisao;

/**
 * Define o comportamento para todos os objectos que destruam o tiny
 */
public interface DestruidorDoTiny {
    /**
     * Trata a colisão com o Tiny
     * @param heroi - Tiny a ser morto
     */
    void trataColisao(Tiny heroi, ResultadoColisao resultado);

    /**
     * Trata a colisão com uma corda
     * @param corda - Corda a fazer desaparecer*/
    void trataColisao(Corda corda, ResultadoColisao resultado);
}
