/* Generated by Together */

package furyPackage;

/**
 * Define comportamento para todos os objectos que podem ser destruídos por bolas de fogo
 */
public interface DestrutivelPeloFogo extends Removivel {
    /**
     * Morte dos objectos destrutíveis pelo fogo
     */
    void morrer(long tempo);

    /**
     * Reduz a energia dos objectos destrutíveis pelo fogo
     */
    void decrementarEnergia(long tempo);

}
