/* Generated by Together */

package furyPackage;

import jge2d.ResultadoColisao;

/**
 * Define o comportamento de todos os objectos que possuem a capacidade de inverter o sentido do seu movimento
 */
public interface Invertivel {
    /**
     * Inverte o movimento do objecto invertivel
     */
    void inverterSentido();

    /**
     * Trata a colisão com uma plataforma
     * @param plataforma - Plataforma com a qual o objecto colide para inverter o sentido
     */
    void trataColisao(Plataforma plataforma, ResultadoColisao resultado );
}
