/* Generated by Together */

package furyPackage;

import jge2d.Ponto;
import jge2d.ResultadoColisao;

public final class MoedaComPorta extends Moeda {

    private Porta porta;

    /**
     * @param posicao - Posicao do objecto no nível
     * @param nivel - Nível ao qual pertence o objecto
     * @param porta - Porta a associar ao objecto activável com porta
     */
    public MoedaComPorta(String nome, Ponto posicao, Nivel nivel, Porta porta, long tempoActual) {
        super(nome, posicao, nivel, tempoActual);
        this.porta = porta;
    }

    public void activar(Tiny heroi, ResultadoColisao resultado) {
        porta.abrir(resultado.tempoColisao);
        super.activar(heroi, resultado);
      }

}
