/* Generated by Together */

package furyPackage;

/**
 * Define o comportamento de todos os objetos que se removem do nível 
 */
public interface Removivel {
    /**
     * Remove um objecto removível do nível 
     */
    void removerDoNivel();
}
