/* Generated by Together */

package furyPackage;

import jge2d.ResultadoColisao;

/**
 * Define comportamento para os objectos com a capacidade de suportar o tiny
 */
public interface Suportavel {

    Tiny getSuportado();

    void suportar(Tiny heroi, ResultadoColisao resultado);

    void desSuportar(long tempo);

    void adicionarSuportadoAosIteraveis(Tiny heroi);
}
