/* cmdline.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "Securitas"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  int porto_arg;	/* porto.  */
  char * contas_arg;	/* Ficheiro com informacao das contas.  */
  char * maquinas_arg;	/* Ficheiro com informacao das maquinas.  */
  int tempo_arg;	/* Tempo de duracao da sessao em minutos.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int porto_given ;	/* Whether porto was given.  */
  int contas_given ;	/* Whether contas was given.  */
  int maquinas_given ;	/* Whether maquinas was given.  */
  int tempo_given ;	/* Whether tempo was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
