/* Generated by Together */

package furyPackage.estados;

import furyPackage.Tiny;

/**
 * Estado que permite ao Tiny seleccionar uma habilidade
 */
public final class EstadoTinySeleccao extends EstadoTiny {

    public EstadoTinySeleccao(Tiny heroi) {
        super(heroi);
    }

    /**
     * Activa no Tiny a habilidade seleccionada
     */
    public void moverCima(long tempo){
       seleccionar(tempo);
    }

    /**
     * Activa no Tiny a habilidade seleccionada
     */
    public void moverBaixo(long tempo){
        seleccionar(tempo);
    }

    /**
     * Selecciona a próxima habilidade
     */
    public void moverDireita(long tempo){
        ((HabilidadeSeleccao)getHeroi().getHabilidadeActual()).moverDireita(tempo);
    }

    /**
     * Selecciona a habilidade anterior
     */
    public void moverEsquerda(long tempo){
       ((HabilidadeSeleccao)getHeroi().getHabilidadeActual()).moverEsquerda(tempo);
    }

    public void parar(long tempo){
    }

    /**
     * diagonalDireita
     *
     * @param tempo long
     */
    public void diagonalDireita(long tempo) {
    }

    /**
     * diagonalEsquerda
     *
     * @param tempo long
     */
    public void diagonalEsquerda(long tempo) {
    }

    public void seleccionar(long tempo) {
        ((HabilidadeSeleccao)getHeroi().getHabilidadeActual()).seleccionarHabilidade();
        getHeroi().mudarEstadoActual(EstadoTiny.SUPORTADO);
        getHeroi().getSprite().setAnimacao(getHeroi().getHabilidadeActual().getAnimacaoFrente(), true, tempo);
        getHeroi().setNomeAnimacaoAnterior(Habilidade.NOME_FRENTE);
    }

    /**
     * iterar
     *
     * @param tempo long
     */
    public void iterar(long tempo) {
    }

    public void desSuportar(long tempo) {
    }
}
