/* Generated by Together */

package furyPackage.estados;

import furyPackage.CampoMagnetico;
import furyPackage.Tiny;
import jge2d.ResultadoColisao;

public class EstadoCampoMagneticoSemTiny extends EstadoCampoMagnetico {

    public EstadoCampoMagneticoSemTiny(CampoMagnetico campo) {
        super(campo);
    }

    public void activar(Tiny heroi, ResultadoColisao resultado) {
        getCampoMagnetico().setLadoDeEntrada(resultado.resultadoObjecto1.tipoColisao);
        heroi.getNivel().adicionarIteravel(getCampoMagnetico());
        getCampoMagnetico().mudarEstado(EstadoCampoMagnetico.CAMPO_COM_TINY);
    }
}
