/* Generated by Together */

package furyPackage.estados;

import furyPackage.Activavel;
import furyPackage.Corda;
import furyPackage.Enganchavel;
import furyPackage.Suportavel;
import jge2d.Ponto;
import jge2d.ResultadoColisao;

/**
 * Define o comportamento da corda no estado enganchada
 */
public class EstadoCordaEnganchada extends EstadoCorda {

    public EstadoCordaEnganchada(Corda corda) {
        super(corda);
    }

    public void trataColisao(Enganchavel enganchado, ResultadoColisao resultado) {
    }

    public void trataColisao(Suportavel plataforma, ResultadoColisao resultado) {
        getCorda().suster(resultado.tempoColisao);
    }

    public void trataColisao(Activavel activavel, ResultadoColisao resultado) {
        getCorda().suster(resultado.tempoColisao);
    }

    public void lancar(Ponto destino, long tempo) {
        getCorda().desenganchar(tempo);
    }

    public void actualizarMovimentoDoDono(long tempo) {
    }

    public void remover(long tempo) {
        getCorda().getSprite().removeSpriteColisionListener(getCorda(), "trataColisao");
        getCorda().desenganchar(tempo);
    }

}
