/* Generated by Together */

package furyPackage.estados;

import furyPackage.CampoMagnetico;
import furyPackage.Tiny;
import jge2d.ResultadoColisao;

public abstract class EstadoCampoMagnetico {

    public static final int CAMPO_SEM_TINY = 0;
    public static final int CAMPO_COM_TINY = 1;

    private CampoMagnetico campoMagnetico;

    public EstadoCampoMagnetico(CampoMagnetico campo) {
        campoMagnetico = campo;
    }

    public CampoMagnetico getCampoMagnetico() {
        return campoMagnetico;
    }

    public abstract void activar(Tiny heroi, ResultadoColisao resultado);

}
