/* Generated by Together */

package furyPackage.estados;

import furyPackage.Activavel;
import furyPackage.Corda;
import furyPackage.Enganchavel;
import furyPackage.Suportavel;
import jge2d.Ponto;
import jge2d.ResultadoColisao;
import jge2d.SpriteCorda;
import jge2d.jogo.movimentos.MovimentoSegmentoRectaUnidireccional;

/**
 * Define o comportamento da corda no estado solta (estado por enganchar quando é lançada)
 */
public class EstadoCordaArrecadada extends EstadoCorda {

    public EstadoCordaArrecadada(Corda corda) {
        super(corda);
    }

    public void trataColisao(Enganchavel enganchado, ResultadoColisao resultado) {
    }

    public void trataColisao(Suportavel plataforma, ResultadoColisao resultado  ){
    }

    public void trataColisao(Activavel activavel, ResultadoColisao resultado ){
    }

    public void lancar(Ponto destino, long tempo){
        getCorda().mudarEstado(EstadoCorda.SOLTA);
        getCorda().setSprite(new SpriteCorda(getCorda().getNome(), getCorda(), new MovimentoSegmentoRectaUnidireccional(getCorda().getHeroi().getSprite().getUltimaPosicao(), destino, getCorda().getVelocidade(), tempo), getCorda().getHeroi().getMovimentoActual()));
        getCorda().getSprite().addSpriteColisionListener(getCorda(), "trataColisao");
        getCorda().getSprite().getMovimento().addMovimentoListener((EstadoCordaSolta)getCorda().getEstado(EstadoCorda.SOLTA));
        getCorda().getNivel().getMapa().addSprite(getCorda().getSprite());
    }

    public void actualizarMovimentoDoDono(long tempo) {
    }

    public void remover(long tempo) {
    }
}
