/* Generated by Together */

package furyPackage.estados;

import furyPackage.Suportavel;
import furyPackage.Tiny;
import jge2d.ResultadoColisao;
import jge2d.jogo.movimentos.Movimento;

/**
 * Define o comportamento do movimento do Tiny
 */
public abstract class EstadoTinyComMovimento extends EstadoTiny {

    private Movimento movimento;

    public void setMovimento(Movimento movimento) {
        this.movimento = movimento;
    }

    public EstadoTinyComMovimento() {
    }

    public EstadoTinyComMovimento(Movimento movimento) {
        this.movimento = movimento;
    }

    public EstadoTinyComMovimento(Tiny heroi, Movimento movimento) {
        super(heroi);
        this.movimento = movimento;
    }

    public Movimento getMovimento() {
        return movimento;
    }

    /**
     * Trata a colisão com objectos de suporte do tiny, e passa o tiny para o estado suportado atribuíndo-lhe a plataforma que o suporta
     */
    public abstract void trataColisao(Suportavel plataforma, ResultadoColisao resultado);

}
