/* Generated by Together */

package furyPackage.estados;

import furyPackage.CampoMagnetico;
import furyPackage.Tiny;
import jge2d.ResultadoColisao;

public class EstadoCampoMagneticoComTiny extends EstadoCampoMagnetico {

    public EstadoCampoMagneticoComTiny(CampoMagnetico campo) {
        super(campo);
    }

    public void activar(Tiny heroi, ResultadoColisao resultado) {
    }
}
