/* Generated by Together */

package furyPackage.estados;

import furyPackage.Tiny;
import jge2d.jogo.movimentos.MovimentoVelocidadeComSentido;

public final class OrientacaoParado extends Orientacao {

    public OrientacaoParado(Tiny heroi) {
        super(heroi);
    }

    public void disparar(long tempo){
        getHeroi().getHabilidadeActual().dispararParado(tempo);
    }

    /**
     * moverDireita
     *
     * @param tempo long
     */
    public void moverDireita(long tempo) {
        ((MovimentoVelocidadeComSentido)getHeroi().getMovimentoActual()).setSentidoDeslocamento(MovimentoVelocidadeComSentido.SENTIDO_DIREITA);
        getHeroi().getSprite().setAnimacao(getHeroi().getHabilidadeActual().getAnimacaoDireita(), false, tempo);
        getHeroi().setNomeAnimacaoAnterior(Habilidade.NOME_DIREITA);
        getHeroi().getNivel().adicionarIteravel(getHeroi());
    }

    /**
     * moverEsquerda
     *
     * @param tempo long
     */
    public void moverEsquerda(long tempo) {
        ((MovimentoVelocidadeComSentido)getHeroi().getMovimentoActual()).setSentidoDeslocamento(MovimentoVelocidadeComSentido.SENTIDO_ESQUERDA);
        getHeroi().getSprite().setAnimacao(getHeroi().getHabilidadeActual().getAnimacaoEsquerda(), false, tempo);
        getHeroi().setNomeAnimacaoAnterior(Habilidade.NOME_ESQUERDA);
        getHeroi().getNivel().adicionarIteravel(getHeroi());
    }

    /**
     * pararAnimacaoFrente
     *
     * @param tempo long
     */
    public void pararAnimacaoFrente(long tempo) {
        getHeroi().getSprite().setAnimacao(getHeroi().getHabilidadeActual().getAnimacaoFrente(), true, tempo);
        getHeroi().setNomeAnimacaoAnterior(Habilidade.NOME_FRENTE);
        ((MovimentoVelocidadeComSentido)getHeroi().getMovimentoActual()).setSentidoDeslocamento(MovimentoVelocidadeComSentido.PARADO);
    }

    /**
     * pararAnimacaoEsquerda
     *
     * @param tempo long
     */
    public void pararAnimacaoEsquerda(long tempo) {
    }

    /**
     * pararAnimacaoDireita
     *
     * @param tempo long
     */
    public void pararAnimacaoDireita(long tempo) {
    }

    /**
     * getSentido
     */
    public int getSentido() {
        return MovimentoVelocidadeComSentido.PARADO;
    }

}
