/* Generated by Together */

package furyPackage.estados;

import furyPackage.Tiny;

public abstract class Orientacao {

    private static int b = 0;
    public static final int ESQUERDA = b++;
    public static final int PARADO = b++;
    public static final int DIREITA = b++;

    private Tiny heroi;

    public Orientacao(Tiny heroi) {
        this.heroi = heroi;
    }

    public Tiny getHeroi() {
        return heroi;
    }

    public abstract void disparar(long tempo);

    public abstract void moverDireita(long tempo);

    public abstract void moverEsquerda(long tempo);

    public abstract void pararAnimacaoFrente(long tempo);

    public abstract void pararAnimacaoEsquerda(long tempo);

    public abstract void pararAnimacaoDireita(long tempo);

    public abstract int getSentido();
}
