/* Generated by Together */

package furyPackage.estados;

import furyPackage.Tiny;
import jge2d.jogo.movimentos.MovimentoVelocidadeComSentido;

public final class OrientacaoEsquerda extends Orientacao {

    public OrientacaoEsquerda(Tiny heroi) {
        super(heroi);
    }

    public void disparar(long tempo){
        getHeroi().getHabilidadeActual().dispararEsquerda(tempo);
    }

    /**
     * moverDireita
     *
     * @param tempo long
     */
    public void moverDireita(long tempo) {
        getHeroi().getOrientacao(Orientacao.PARADO).moverDireita(tempo);
    }

    /**
     * moverEsquerda
     *
     * @param tempo long
     */
    public void moverEsquerda(long tempo) {
    }

    /**
     * pararAnimacaoFrente
     *
     * @param tempo long
     */
    public void pararAnimacaoFrente(long tempo) {
    }

    /**
     * pararAnimacaoEsquerda
     *
     * @param tempo long
     */
    public void pararAnimacaoEsquerda(long tempo) {
        if (getHeroi().isRebolar()) {
            getHeroi().getSprite().setAnimacao(getHeroi().getHabilidadeActual().getAnimacaoEsquerda(), false, tempo);
            getHeroi().setNomeAnimacaoAnterior(Habilidade.NOME_ESQUERDA);
            getHeroi().deixarDeRebolar();
        }
        ((MovimentoVelocidadeComSentido)getHeroi().getMovimentoActual()).setSentidoDeslocamento(MovimentoVelocidadeComSentido.SENTIDO_ESQUERDA);
    }

    /**
     * pararAnimacaoDireita
     *
     * @param tempo long
     */
    public void pararAnimacaoDireita(long tempo) {
    }

    /**
     * getSentido
     */
    public int getSentido() {
        return MovimentoVelocidadeComSentido.SENTIDO_ESQUERDA;
    }

}
