/* opts.h */

/* File autogenerated by gengetopt version 2.7.1  */

#ifndef _opts_h
#define _opts_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#ifndef PACKAGE
#define PACKAGE "schedule"
#endif

#ifndef VERSION
#define VERSION "0.01"
#endif

struct gengetopt_args_info
{
  char * conf_arg;	/* Ficheiro de configuração.  */
  int time_slice_arg;	/* quantidade de quanta do time-slice.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int conf_given ;	/* Whether conf was given.  */
  int time_slice_given ;	/* Whether time_slice was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _opts_h */
