/* ps_opts.h */

/* File autogenerated by gengetopt version 2.7.1  */

#ifndef _ps_opts_h
#define _ps_opts_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#ifndef PACKAGE
#define PACKAGE "ps_schedule"
#endif

#ifndef VERSION
#define VERSION "0.01"
#endif

struct gengetopt_args_info
{
  int freq_arg;	/* frequencia de actualizacao.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int freq_given ;	/* Whether freq was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _ps_opts_h */
